apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ default .Values.secret.refreshInterval "1h0m0s" }}
  secretStoreRef:
    name: {{ .Values.secret.secretStoreName }}
    kind: {{ .Values.secret.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.secret.secretName | default .Values.secret.name }}
    creationPolicy: {{ .Values.secret.secretCreationPolicy | default "Owner" }}
  {{- if .data }}
  data: {{ toYaml .Values.secret.data | nindent 4 }}
  {{- end -}}
  {{- if .dataFrom }}
  dataFrom: {{ toYaml .Values.secret.dataFrom | nindent 4 }}
  {{- end -}}
