apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
  namespace: {{ .Values.namespace }}
data:
  WAL_S3_BUCKET: {{ .Values.backup.bucket }}
  WAL_BUCKET_SCOPE_PREFIX: ""
  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '{{ .Values.backup.schedule }}'
  AWS_REGION: {{ .Values.backup.region }}
  WALG_DISABLE_S3_SSE: "true"
  BACKUP_NUM_TO_RETAIN: "{{ .Values.backup.retainCount }}"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_AWS_REGION: {{ .Values.backup.region }}
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_WAL_BUCKET_SCOPE_PREFIX: ""
  CLONE_WAL_S3_BUCKET: {{ .Values.backup.bucket }}
  CLONE_AWS_S3_FORCE_PATH_STYLE: "true"
