name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: add repo
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      - name: build deps
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm dependency build
      - name: lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - name: lint strict
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - run: sed -i -e "s#__AWS_ACCESS_KEY_ID__#${AWS_ACCESS_KEY_ID}#g" values.yaml
      - run: sed -i -e "s#__AWS_SECRET_ACCESS_KEY__#${AWS_SECRET_ACCESS_KEY}#g" values.yaml
      - name: add repo
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      - name: build deps
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm dependency build
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade postgres-operator . --install --namespace=postgres-operator --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
